AWS_ACCESS_KEY_ID:         AKIAJ2MBIXRIB3K4Y64A
AWS_SECRET_ACCESS_KEY:     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
S3_BUCKET_NAME:            brunoswebsiteimages

recaptcha_private_key:     6LenRykTAAAAAG-6YTDp11SB6x6HGJatOnarEp-1
recaptcha_public_key:      6LenRykTAAAAAFwOE-gsrFxU_SZkP96_7aOrjuLI